import canonicalLaneMathlib.AdmissibleClass
import ChemicalEngineeringCatalysisChemicalLemmaCanonicalLaneLean.CatalysisReactionKinetics
import ChemicalEngineeringCatalysisChemicalLemmaCanonicalLaneLean.MolecularOrbitalTheoryBridge
import ChemicalEngineeringCatalysisChemicalLemmaCanonicalLaneLean.ThermodynamicEquilibriumBridge

namespace HautevilleHouse
namespace ChemicalEngineeringCatalysisChemicalLemmaCanonicalLaneLean

def ConstrainedCatalysisClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_catalysis_endgame (A : AdmissibleClass) :
    ConstrainedCatalysisClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end ChemicalEngineeringCatalysisChemicalLemmaCanonicalLaneLean
end HautevilleHouse
